name: signalp
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - scikit-learn>=1.0.0
  - scipy>=1.7.0
  - seaborn>=0.11.0
  - tqdm>=4.46.0
  - typing-extensions>=3.7.4
  - pip
  - pip:
    - torch>=1.7.0
    - tokenizers>=0.9.0
